name: Lint and Commit
on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1
      with:
        gi thub_token: ${{ secrets.github_token }}
        auto_fix: ${{ github.event_name == 'pull_request' }}
        black: true
        flake8: true
