name: My Workflow for Pep08

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PEP8
      uses: quentinguidee/pep8-action@v2.0.13-dev
      with:
        arguments: '--max-line-length=120'
