name: Pep8 with push
on: [push]
jobs:
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: 'Run PEP8'
      - uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
